import {
  AlertCircle,
  AlertTriangle,
  Activity,
  ArrowRight,
  BarChart,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Database,
  Download,
  Edit,
  Eye,
  FileText,
  Heart,
  HelpCircle,
  Home,
  Inbox,
  Loader,
  Loader2,
  LogOut,
  Moon,
  MoreVertical,
  Plus,
  RefreshCw,
  Search,
  Server,
  Settings,
  Sun,
  Trash,
  User,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
} from 'lucide-react';

export const Icons = {
  logo: Database,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  edit: Edit,
  eye: Eye,
  moreVertical: MoreVertical,
  plus: Plus,
  search: Search,
  refresh: RefreshCw,
  loader: Loader,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: AlertCircle,
  help: HelpCircle,
  user: User,
  settings: Settings,
  creditCard: CreditCard,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  server: Server,
  database: Database,
  activity: Activity,
  fileText: FileText,
  wrench: Wrench,
  dashboard: Home,
  heart: Heart,
  arrowRight: ArrowRight,
  barChart: BarChart,
  wifi: Wifi,
  wifiOff: WifiOff,
  inbox: Inbox,
  download: Download,
  x: X,
};